### PR TITLE
DAG-1935: Have better messages when doing resmoke calls

### PR DESCRIPTION
**Pull request by zamj**
[Successful patch](https://spruce.mongodb.com/task/mongodb_mongo_master_generate_tasks_for_version_version_gen_patch_d8ce3ee2e020d1ab2fa611a2a0f0a222b06b9779_63222a26e3c33123f006c13a_22_09_14_19_23_34/logs?execution=0)
[Patch with resmoke error](https://evergreen.mongodb.com/filediff/631badee0305b92ba80bceb6/?file_name=evergreen%2Fbuild_variant_generate.sh&patch_number=0)
[Error log](https://evergreen.mongodb.com/lobster/evergreen/task/mongosync_rhel80_build_variant_gen_patch_ea007a3f028bccbc41f5d5a60df1d4e0dffc3503_631badee0305b92ba80bceb6_22_09_09_21_19_51/1/task#bookmarks=0%2C501&l=1&shareLine=479)

### CODE REVIEW

**Review by zituo-jin — APPROVED** [review]

**Comment by zamj** [comment]
evergreen merge

**Comment by zamj** [comment]
evergreen merge

**Comment by zamj** [comment]
evergreen merge

**Comment by zamj** [comment]
evergreen merge

**Comment by zamj** [comment]
evergreen merge

**Comment by zamj** [comment]
evergreen merge

**Pull request merged**
